### ISSUE TITLE
还在维护吗

### ISSUE THREAD

**Issue by nighca** [thx/crox#4]
RT.

还适合在生产环境使用吗

**Comment by wangjeaf** [comment]
在维护，阿里这边正在生产环境中使用

**Comment by nighca** [comment]
谢谢~

我们想使（大概前端*4，后端*4，php的项目），有啥坑的预警或者建议不？

**Comment by nighca** [comment]
另，求教

https://github.com/thx/crox/blob/master/lib/crox_extra.php#L36

这行为什么要使用GB2312字符集呢，而不是UTF-8

**Comment by panasonic** [comment]
在维护，欢迎使用，欢迎提bug，欢迎吐槽！
@nighca  当时也尝试了utf-8，好像比较麻烦，就暂时用gb2312了。这个编码问题，我再研究下。

**Comment by nighca** [comment]
赞，另外我周末试着搞了下，需求基本都被满足了，唯一缺憾在于模板的嵌套是同一个作用域，意味着一个通用的页面组件如header（需要一些变量如header_title，header_right_link），使用的时候需要这样：

```
{{set header_title = "..."}}
{{set header_right_link = root.xxx.yyy}}
{{include "widget/header/header.tpl"}}
```

这样一来污染外部作用域，二来模板嵌套的时候可能会发生变量被内部模板覆盖。

你们有遇到过这样的问题吗，有啥解决方法没？

**Comment by panasonic** [comment]
目前都是全局的，不支持函数/过程调用。好像只能加前缀来避免冲突了。

**Comment by nighca** [comment]
谢谢~

我fork了代码，想自己添加{{include "path" a=xxx b=yyy}}的语法，发现[parse](https://github.com/thx/crox/blob/master/build/crox-all.js#L325)的过程太难阅读、修改了，有相关资料或者哪位指导下不？

**Comment by nighca** [comment]
好像是根据grammar.txt生成的代码？求指导是啥工具，依赖里边没找着。。

**Comment by nighca** [comment]
搞定了，多谢！
